### ISSUE TITLE
Documentation of an example custom processor?

### ISSUE THREAD

**Issue by stephengardner** [cazzer/gulp-selectors#30]
I'm trying to implement some custom logic and I imagine this would be a great use case for a custom processor but the current documentation somehow leaves me completely confused.  Is there an example of a custom processor in full?

**Comment by cazzer** [comment]
Custom processors are best suited for custom parsing logic and are not well documented, so allow me to elaborate:
```js
gs.run({
  './path/to/custom/processor': ['html']
})
```
Gulp Selectors with `require` the file path which is specified and expect it to export a function that takes three arguments: `file`, `classLibrary`, and `idLibrary`. You can take a look at how [the HTML processor](https://github.com/cazzer/gulp-selectors/blob/master/lib/processors/html.js) works as an example.

Note that processors run in the order specified, so if you depend on already having collected a full library or `id`s and `class`es for your processor run it last:
```js
gs.run({
  'css': ['scss', 'css'],
  'html': ['haml', 'html'],
  './path/to/custom/processor': ['css', 'html']
})
```

Good luck and let me know if you have any further questions.
